apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::677432355836:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-QPBHVDJ01VQC
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::677432355836:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-05T20:40:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1669"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 955e7e15-246c-4cd4-b549-9a7a4cea5ca4